### ISSUE TITLE
Some compilers do not support -march=haswell

### ISSUE THREAD

**Issue by bestgopher** [darrenldl/reed-solomon-erasure#113]
I catched some build errors:
```
warning: reed-solomon-erasure@6.0.0: simd_c/reedsolomon.c:1:0: error: bad value (haswell) for -march= switch
warning: reed-solomon-erasure@6.0.0:  /* reedsolomon.c - SIMD-optimized Galois-field multiplication routines
warning: reed-solomon-erasure@6.0.0:  ^
```
The reason may be that some specific version of compilers does not support `-march=haswell`.
```shell
-> root@AAA ~git:(main) 101? # gcc -march=native -E - < /dev/null
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
-> root@AAA ~git:(main) ? # gcc -march=haswell -E - < /dev/null
# 1 "<stdin>"
<stdin>:1:0: error: bad value (haswell) for -march= switch
```

Could we sure that compiler supports `-march=haswell` when set build flag?

**Comment by nazar-pc** [comment]
Which version of GCC is it specifically? Might be just too old to know about Haswell, in which case I don't think we care about it all that much.

**Comment by bestgopher** [comment]
> Which version of GCC is it specifically? Might be just too old to know about Haswell, in which case I don't think we care about it all that much.

```
-> root@AAA ~ ? # gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright © 2015 Free Software Foundation, Inc. 
```

**Comment by nazar-pc** [comment]
GCC 4.8.5 is from 2015, I'm fairly certain no one will bother doing anything to support it. You should really upgrade to more modern and supported OS or install newer GCC in some way yourself.

**Comment by bestgopher** [comment]
> GCC 4.8.5 is from 2015, I'm fairly certain no one will bother doing anything to support it. You should really upgrade to more modern and supported OS or install newer GCC in some way yourself.

Okey. Thanks for your reply.
