### ISSUE TITLE
`Error` type should implement `std::error::Error`.

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [darrenldl/reed-solomon-erasure#17]
Common error chaining crates (`error-chain`, `failure`, etc...) require all error types in their chains implement the trait `std::error::Error`. Currently, `reed_solomon_erasure::Error` does not implement this trait, thus excluding it from being used alongside many popular approaches to error handling.

**Comment by darrenldl** [comment]
Thanks for the suggestion!

Out of curiousity, are you using the crate or are you just fixing crates online?

Tracked at PR #18

**Comment by DrPeterVanNostrand** [comment]
Thanks for the quick response! Yup, I'm working on [a piece of software](https://github.com/poanetwork/hbbft) that is using the `reed-solomon-erasure` crate. I'll check out the PR now.

**Comment by darrenldl** [comment]
@DrPeterVanNostrand `reed-solomon-erasure v3.1.0` has been published to crates.io. Thanks again for the suggestion! Feel free to open another issue if you find the library to be missing anything.

As a side note, the paper that your project is based on("Honey Badger of BFT Protocols") uses zfec for its implementation, which I'm not sure if this library is compatible with, though examining very briefly it seems that they should be compatible. But you'll need to test that if that's desired.

**Comment by DrPeterVanNostrand** [comment]
Ok awesome, I appreciate letting me know about the version bump! I'll bring up the zfec/reed-solomon compatibility thing with the rest of the team.
