### ISSUE TITLE
Compiling for android platform

### ISSUE THREAD

**Issue by EvgenKor** [darrenldl/reed-solomon-erasure#23]
Hi! I want to use your library for another rust project which compiled for android platform. Unfortunately when I try to build my project, I have a following error:

`cargo:warning=simd_c/reedsolomon.c:1:0: error: unknown value 'native' for -march`

I inspected your code and found a problem: gcc compler for android (aarch64-linux-android-gcc) doesn't support -march flag. Project builds successfully when I remove this flag from the build.rs file. Could you please add some option for your library to disable this compiler flag?

**Comment by darrenldl** [comment]
Hello, thanks for reporting!

I've updated `build.rs` on the dev branch, see if it works on your side.

If it does I'll open a PR and publish it as soon as all CI stuff are finished.

**Comment by darrenldl** [comment]
I have opened a PR just cause the CI stuff takes a while. See #24

**Comment by darrenldl** [comment]
Turns out to be a very simple fix(just need to remove a duplicate macro definition), I've updated the PR accordingly.

One potential issue about using the library on Android is I'm not sure how well GCC generates the SIMD assembly code, so the performance might not be as fast as it is on PCs.

But I don't think that's a massive problem as the library's performance should be above the bandwidth of most mediums with common data parity configuration anyway.

**Comment by darrenldl** [comment]
Alright so that broke stable/beta build, I just renamed it to something else and now it should work on all 3 rust channels.

Adding conditional compilation via `build.rs` in test code is too much hassle for me, so I'll just stick with the current solution.

**Comment by darrenldl** [comment]
@EvgenKor Any updates from your side? I don't have an Android development platform, so I can't test the fix easily.

Anyhow I will be incredibly busy for next 1-2 months, apologies in advance if I don't get back to you quickly.

**Comment by EvgenKor** [comment]
@darrenldl Sorry for the long delay from my side. I hasn't possibilities to answer you for last two weeks. I tested development branch and all works well, thank you very much!
I think you can add in your build.rs one more exception for platform 'ios' (line 160)

**Comment by darrenldl** [comment]
@EvgenKor Incredibly sorry for the long delay, as mentioned in last comment, past 1-2 months were extremely busy for me, dealing with thesis etc. Just handed in the thesis 3 days ago actually. I was unable to go through all GitHub notifications in detail during the time, missing your comment as a result.

I'll still need to prepare materials for submission to a conference for next 3 weeks, but I'll try to wrap this up and publish this version in next 1-2 days.

Apologies again.

**Comment by darrenldl** [comment]
Okay, so I couldn't find any GitHub notification for this issue when you last commented, which was probably the other reason I failed to reply to you on top of being busy. Not really sure what happened with the missing email notification.

**Comment by darrenldl** [comment]
Hey @EvgenKor, `reed-solomon-erasure` v3.1.1 has been published on creates.io
