### ISSUE TITLE
Extract core functionality to a "core" module

### ISSUE THREAD

**Issue by rphmeier** [darrenldl/reed-solomon-erasure#41]
I think a reasonable API would be to have the following module structure:

```
lib 
  - error
  - core [contains ReedSolomon and ShardByShard]
  - galois_8 [re-exports ReedSolomon and ShardByShard over GF(2^8)]
  - galois_16 [re-exports ReedSolomon and ShardByShard over GF(2^16)]
```

A typical user would access
```rust
use reed_solomon::galois_8::ReedSolomon;

let rs = ReedSolomon::new(2, 3); // no issues with type inference.
```

**Comment by darrenldl** [comment]
@rphmeier this is resolved or superseded by the current design right?

**Comment by rphmeier** [comment]
I guess every aspect of it except that the `core` stuff is still in `lib.rs`.

**Comment by darrenldl** [comment]
Ah right. I'll move the two chunks of code into core to organise better then.

The trait implementations will continue to be in `lib.rs` then I guess?
