### ISSUE TITLE
Added contributors of galois_16 to LICENSE file

### ISSUE THREAD

**Issue by darrenldl** [darrenldl/reed-solomon-erasure#51]

**Comment by darrenldl** [comment]
@rphmeier, @drskalman and @burdges

Personally, due to the significant amount of work done by you guys, I feel being added to LICENSE file is appropriate and natural.

My understanding is if things get legal then joint copyright can get messy, which I don't exactly anticipate to happen, but I am also very naive and inexperienced in the handling of things like this.

Do you guys have any advice on this? Would you prefer the copyright as it stands? Or would a joint copyright feel more appropriate?

**Comment by darrenldl** [comment]
Closing issue for now due to no response.

Feel free to reopen this issue or contact me via email etc if further discussion is desirable.

**Comment by rphmeier** [comment]
Hi Darren,

That's kind, but I don't have a strong preference since it's the MIT license anyway! We are using it at the moment in some GPL3 open-source software

Cheers
