### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by darrenldl** [darrenldl/reed-solomon-erasure#54]
Hey @rphmeier, @drskalman and @burdges,

I'm updating the credits section w.r.t. galois16 and other code contributions, I can see contributions from @rphmeier  and @drskalman in the charts, but not @burdges. But @burdges has been involved since the beginning of the conversation, so I'm confused about the exact involvements.

Mind if someone clarify who I should list as contributors?

Cheers

**Comment by darrenldl** [comment]
Please do chime if I missed anyone else.

I've just started my PhD and likely to have lost track of myriad things, sorry!

**Comment by rphmeier** [comment]
Hey Darren,

@drskalman and I collaborated on the implementation work; with advice from @burdges. Jeff's contribution was non-negligible so I'd say it's fair to include him on a list of contributors (even though there are no commits :) ). Up to you as the maintainer.

Cheers

**Comment by darrenldl** [comment]
Ah okay, that makes more sense. I was thinking you guys were collaborating behind the scenes, but I wasn't sure.

I'll just list everyone down in alphabetical order unless you guys have a different preference.

**Comment by darrenldl** [comment]
Which format would you guys prefer?

- `Full name [github user name](github user profile link)`
- `[github user name](github user profile link)`

**Comment by rphmeier** [comment]
No strong opinion, mild preference for option 1. Thanks Darren.
